### ISSUE TITLE
Issue with PlaceOrder SMS/Email

### ISSUE THREAD

**Issue by anupam42** [anupam42/PG-DAPP#1]
Items with count 0, while ordering should pop-pop up for count. while submitting the order.
("YES EDIT", "NO THANKS");

**Comment by anupam42** [comment]
I have fixed this issue, Please test.

**Comment by anupam42** [comment]
Its Not yet fixed , please verify.

**Comment by anupam42** [comment]
Its Not yet fixed , please verify.

**Comment by AlienHu** [comment]
I have fixed this isuue , please verify

**Comment by ParshuM** [comment]
closed
