### ISSUE TITLE
take order  kot alignment ( totalquantities) like that showing 

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#115]
![kots](https://cloud.githubusercontent.com/assets/20481136/17271671/7bf62134-569f-11e6-9210-628b55f04d83.png)

**Comment by anupam42** [comment]
Issue fixed Please do review :+1: 
![alignment fixed](https://cloud.githubusercontent.com/assets/16332264/17322345/cafe6fe4-58ba-11e6-96bd-aa7ab2cc0f02.png)

**Comment by ParshuM** [comment]
not done

**Comment by ParshuM** [comment]
closed
