### ISSUE TITLE
reservation ,Showing Employee name.

### ISSUE THREAD

**Issue by praveenpss** [anupam42/PG-DAPP#117]
hi team 

you make in employee name it should taking number
![youshouldmake employe](https://cloud.githubusercontent.com/assets/20493150/17271717/e73a248a-56a0-11e6-992c-7aa35c6aea04.png)

**Comment by ParshuM** [comment]
employee name not showing

**Comment by ParshuM** [comment]
![resttt](https://cloud.githubusercontent.com/assets/20481136/17644208/62eb9886-619e-11e6-9999-e4af65718dab.png)

**Comment by ParshuM** [comment]
not showing employee name

**Comment by ParshuM** [comment]
closed
