### ISSUE TITLE
#short-keys 

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#118]
close button for  shortcut in not properly all modules 
![shortkeys](https://cloud.githubusercontent.com/assets/20481136/17271894/0491588c-56a6-11e6-970e-780d11a54fd4.png)

**Comment by anupam42** [comment]
Issue fixed please do review :+1: 
![close button alligned](https://cloud.githubusercontent.com/assets/16332264/17323495/07076e00-58c0-11e6-8364-6e8385d999a2.png)

**Comment by ParshuM** [comment]
not done

**Comment by ParshuM** [comment]
closed
