### ISSUE TITLE
#Quantity Stocks 

### ISSUE THREAD

**Issue by jarvish21** [anupam42/PG-DAPP#120]
![img_20160731_095908863](https://cloud.githubusercontent.com/assets/20481181/17274682/fd93525a-570a-11e6-9c50-87cbac944d1d.png)

Enhancement for quaqntity stocks....

**Comment by moghribalakrishna** [comment]
Should be finished in another 1-2 days. Top priority.

**Comment by jarvish21** [comment]
- [ ] We should analyse completely side effect of these changes.
- [ ] Self prepared Items shouldn't appear in low inventory report, Supplier, Receivings and shouldn't be shown even in place-order.

**Comment by jarvish21** [comment]
- [x] for self prepared items we should remove quantity and reorder fields.

**Comment by jarvish21** [comment]
- [x] make proper linking for index file based on app type

**Comment by saichaitanyaeruvaram** [comment]
Inputs from Sai & Gajanan

Summarising the requirement and feature
1. For Restaurant, Menu and Raw Ingredients Should be Separate.
2. And in Menu, there should be two categories, dosas for example no serial number, no reorder level, and for coca-coal, ice cream u can have the existing fields
3. Dosas and raw ingredients should be linked. raw ingredients should be automatically reducing

**Comment by moghribalakrishna** [comment]
There is separate issue has been logged for smart inventory management, this issue was meant to deal with, wrong inventory deductions in Restaurant.
Other suggestions have been moved to issue #216,

**Comment by moghribalakrishna** [comment]
@jarvish21 Gang explain this feature and ask Gaju/Parsu to verify what is intended and also ask the close this if it meets its requirement.

**Comment by Jnanumogri** [comment]
assign to Gajanan

**Comment by ParshuM** [comment]
closed

**Comment by ParshuM** [comment]
need to be Gangadhar  help

**Comment by ParshuM** [comment]
![pk](https://cloud.githubusercontent.com/assets/20481136/17709417/a14bbdbc-6406-11e6-80f1-3563d02cefcb.png)
Prepared items should not display in inventory report and its displaying supplier name in menuitem and prepared   should not show in supplier reports

**Comment by AlienHu** [comment]
@saichaitanyaeruvaram  @moghribalakrishna  what about this issue?

**Comment by AlienHu** [comment]
Disabled supplier select option for prepared items , @ParshuM please consult if you get any doubts while testing

**Comment by ParshuM** [comment]
closed
