### ISSUE TITLE
Reservation :: Search should support search by customer name or mobile number

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [anupam42/PG-DAPP#127]
When customer calls and makes a reservation, he provides name and contact number.

When he comes to the restaurant, we should be able to tell his table based on his name/number.

**Comment by moghribalakrishna** [comment]
Anup, Take try to fix this asap.

**Comment by jarvish21** [comment]
reservation search based on contact number is done do test it...

**Comment by ParshuM** [comment]
closed
