### ISSUE TITLE
# retail sales cart

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#129]
make edit button on sales cart (:-new users can find)

![sales](https://cloud.githubusercontent.com/assets/20481136/17275673/7eb26b60-572d-11e6-8ea3-68cf8a5dd4e6.png)

**Comment by anupam42** [comment]
please do review issue is fixed i have added edit icon so u can edit :+1: 
![edit option added](https://cloud.githubusercontent.com/assets/16332264/17366554/7d60a83e-59a9-11e6-880e-a58a1d497412.png)

**Comment by ParshuM** [comment]
closed
