### ISSUE TITLE
Automatic Price Calculator 

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [anupam42/PG-DAPP#131]
While adding items.. unit price will be specified. Example 1 Kg Rice Rs. 60. 1 ltr Oil Rs. 90.

while sales, user can edit the quantity like 2.2 kg rice and price should update automatically and the left over stock should get updated automatically.

Real Life Use Cases:
Vegetable shops, retail outlets selling rice, dal etc.

**Comment by moghribalakrishna** [comment]
Closing this as this requirement is moved to new issue #216
