### ISSUE TITLE
Reservation  Delete PopUP

### ISSUE THREAD

**Issue by praveenpss** [anupam42/PG-DAPP#132]
hi team 
when  make reservation their one delete option is their when we are click on their it will not asking you want delete it will deleted automatically you will make their ask to for delete

![delete](https://cloud.githubusercontent.com/assets/20493150/17282324/48a1a870-57c2-11e6-8ca3-f09cbb861bcc.png)
 asit is same problem in taking order when making bill in restaurant taking order ok

**Comment by ParshuM** [comment]
closed

**Comment by anupam42** [comment]
@moghribalakrishna  anna issue is already fixed

**Comment by ParshuM** [comment]
closed
