### ISSUE TITLE
Recevings Screen

### ISSUE THREAD

**Issue by anupam42** [anupam42/PG-DAPP#14]
Remove Supplier Field.. And do proper UI Alignment

**Comment by anupam42** [comment]
Issue is not properly defined can i get the screenshot of the issue so that according to that i can change :+1:

**Comment by moghribalakrishna** [comment]
Is it Done?

**Comment by anupam42** [comment]
Please do review issue is fixed :+1:

**Comment by ParshuM** [comment]
closed
