### ISSUE TITLE
Retail&Restaurant: Default Values on all he Drop Downs.

### ISSUE THREAD

**Issue by anupam42** [anupam42/PG-DAPP#143]
Example
- [ ] For thousand and Language separator in Localization settings.
- [ ] Check and comment here for other screens.

**Comment by ParshuM** [comment]
closed

**Comment by ParshuM** [comment]
Not Done

**Comment by ParshuM** [comment]
Not Done

**Comment by anupam42** [comment]
please do review issue is fixed :+1:

**Comment by Jnanumogri** [comment]
its not showing default value in reservation window

**Comment by ParshuM** [comment]
its not showing default value in all reports restaurant and retails on window   (all screen date range)
![repots all](https://cloud.githubusercontent.com/assets/20481136/17611390/6e98996c-6064-11e6-8211-ef2a682c5211.png)

**Comment by ParshuM** [comment]
closed

**Comment by ParshuM** [comment]
![sales](https://cloud.githubusercontent.com/assets/20481136/17645417/6bab113e-61c3-11e6-99c1-eac7aeaea189.png)
Reports in that Detailed reports employee Default Value Drop Down not showing check screen short
