### ISSUE TITLE
Restaurant:  Dont make Table description compulsory

### ISSUE THREAD

**Issue by vinodshidlani** [anupam42/PG-DAPP#148]
in new creat table discription option should not compulsory...will you remove that compulsory option,,

![vin](https://cloud.githubusercontent.com/assets/20521598/17315906/4def6800-588d-11e6-81ae-6714cbb399a6.png)

**Comment by anupam42** [comment]
Please do review issues is fixed :+1: 
![desc mandatory field removed](https://cloud.githubusercontent.com/assets/16332264/17356902/9bcc4e72-5977-11e6-85cf-ff08eb7b57a9.png)

**Comment by ParshuM** [comment]
closed
