### ISSUE TITLE
# retails and restaurants  carts 

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#149]
overlap of paymentstype 

![parshu](https://cloud.githubusercontent.com/assets/20481136/17316043/5bf4112a-588e-11e6-8286-f7eb1901eef0.png)

**Comment by anupam42** [comment]
Please do review :+1: issue is fixed 

![bill details alignment done](https://cloud.githubusercontent.com/assets/16332264/17357417/3321c5fc-597a-11e6-986c-891e75d63f14.png)

**Comment by ParshuM** [comment]
not done

**Comment by anupam42** [comment]
please do review issue is fixed :+1: 
![bill details alignment done](https://cloud.githubusercontent.com/assets/16332264/17357465/47c3bc36-597a-11e6-85ac-7a3dacff4ae0.png)

**Comment by ParshuM** [comment]
closed
