### ISSUE TITLE
Detailed Sales Report 

### ISSUE THREAD

**Issue by moghribalakrishna** [anupam42/PG-DAPP#150]
Changing subtotal to Unit Price in Detailed Sales report.
1) In detailed sales Report, it looks like subtotal is nothing but the Unit price of the Product that we're selling, Confirm this and if that's the case then change its name From "Subtotal" to "Unit Price"

**Comment by anupam42** [comment]
please do review issue is fixed :+1: 
![subtotal unitprice](https://cloud.githubusercontent.com/assets/16332264/17366777/8d26a48e-59aa-11e6-960c-8d90fbb36118.png)

**Comment by ParshuM** [comment]
closed

**Comment by ParshuM** [comment]
![unit price showing zero](https://cloud.githubusercontent.com/assets/20481136/17373582/72867624-59c6-11e6-9fe8-663daec1419f.png)

**Comment by ParshuM** [comment]
unit price showing zero in sales details reports

**Comment by samurailens** [comment]
@anupam42  : when we have multiple payment types, can we put them on below other ?

cash       : 400
gift card : 200 

instead of comma
