### ISSUE TITLE
# Reservation 

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#154]
alignment of cart
![alignment of cart](https://cloud.githubusercontent.com/assets/20481136/17333951/15ec0c64-58f2-11e6-8145-5b088784ca0a.png)

**Comment by anupam42** [comment]
Please do review issue is fixed :+1: 
![reservation](https://cloud.githubusercontent.com/assets/16332264/17357358/c8989878-5979-11e6-8b56-927750f5fa5a.png)

**Comment by ParshuM** [comment]
closed
