### ISSUE TITLE
Cancel Button for Edit Field in Sales Screen

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [anupam42/PG-DAPP#17]
After adding some items in cart.
1. No line or color change between two items... no border.. everything is white

Now I want to change value/price. So I double click 1 line.
1.  All the lines are changed into edit field.2
2. Even after pressing Save, it doesn't go back out of edit field
3. No cancel option
4. If serial number is present then it is out of alignment

![alignement](https://cloud.githubusercontent.com/assets/10721851/16900366/c78aac46-4c40-11e6-959f-b77f18d67103.png)

**Comment by jarvish21** [comment]
works fine
