### ISSUE TITLE
Item:wrong hover over for Items

### ISSUE THREAD

**Issue by Jnanumogri** [anupam42/PG-DAPP#174]
when we hover in the item view it is showing wrong means at the place of details its showing update
![view item in while we updating its showing details and at the place of details its showing update](https://cloud.githubusercontent.com/assets/20493114/17455535/fb86b91c-5bd7-11e6-934c-62010b31b8a4.png)

**Comment by anupam42** [comment]
![hover exchanged](https://cloud.githubusercontent.com/assets/16332264/17455551/aa0422ae-5bd8-11e6-9f30-aaef482838a2.png)
Please do review issue is fixed :+1:
