### ISSUE TITLE
Alignment and UI

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [anupam42/PG-DAPP#18]
Listing All Alignment Issues
- [ ] **CheckOut Screen**

![checkoutscreen](https://cloud.githubusercontent.com/assets/10721851/17089155/1b807b0e-5241-11e6-9f16-36ea756cb0ca.png)
- [ ] **Add Itmes**
  ![additem_alignment](https://cloud.githubusercontent.com/assets/10721851/17089199/aa8b47b6-5241-11e6-9662-c30a56c128ff.png)
- [ ] **Reports** :: Many places check thoroughly, listing few sample places
1. Summary Reports -> Items
2. Inventory Summary 
   ![alignment](https://cloud.githubusercontent.com/assets/10721851/17123754/6bcf615c-5303-11e6-84c3-cdf02f3c503f.png)

**Comment by ParshuM** [comment]
not done

**Comment by anupam42** [comment]
Please do review issue is fixed :+1: 
![itemview](https://cloud.githubusercontent.com/assets/16332264/17366886/2b3c14f6-59ab-11e6-8fc5-48d0e89ac408.png)
![itemsummary](https://cloud.githubusercontent.com/assets/16332264/17366896/30efc2d0-59ab-11e6-8ecd-184325f71398.png)
![salesscreen](https://cloud.githubusercontent.com/assets/16332264/17366901/37aab8dc-59ab-11e6-8f81-dc9adbfdb6df.png)

**Comment by ParshuM** [comment]
closed
