### ISSUE TITLE
Expiry Date Confusion

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [anupam42/PG-DAPP#182]
Suppose there is an item which expires on Sept 30.
Now, I order fresh, the expiry date is different (Nov 30). 
How is this handled?

**Comment by samurailens** [comment]
@anupam42 @GanuM 

In 'Receivings' screen - we should have a field that would ask for expiry date. 
This field would probably be a radio button for each item received. Screenshot below shows some options. We can categorize and then reduce the options - like - we should detect the item that is being received and then show options to user based on the item.. Example : Beverages have 6 months default expiry date. We can give 3, 6 or 9 as options - assuming various beverages available in market. I think we should make our system understand at least categories if not each specific item.

![image](https://cloud.githubusercontent.com/assets/5208310/17456586/8b31196e-5bfa-11e6-87f5-aeb758376bf8.png)

**Comment by moghribalakrishna** [comment]
Assigning it to Gangadhar, discuss this with Sachin.

**Comment by saichaitanyaeruvaram** [comment]
If barcode is present. There will be different barcodes for different expiry dates. This issue will not arise.
If item doesn't have barcode, user should create name_expiry_date.
Closing for now.
