### ISSUE TITLE
reservation not able to make payment 

### ISSUE THREAD

**Issue by gajananalienhu** [anupam42/PG-DAPP#190]
for reserved table to able to make payment

**Comment by AlienHu** [comment]
please cross check once again .... post some screen shots .. bcz its working for me

**Comment by samurailens** [comment]
@gajananalienhu @GanuM  : any updates?

**Comment by AlienHu** [comment]
No updates , created one more issue  #424 related to this , i'm closing this issue we can look at this after fixing that new issue  #424
