### ISSUE TITLE
menu item for prepared items we have to remove stock reorder  

### ISSUE THREAD

**Issue by gajananalienhu** [anupam42/PG-DAPP#191]
while creating  prepared item  current quantity reorder level suppliers serial number we have to hide this

**Comment by AlienHu** [comment]
@gajananalienhu  @samurailens  i think we shoul not hide it .... we can allow user to add item with ou wihout entering the values for those fields

**Comment by jarvish21** [comment]
did only for desktop need to study its affect on reports and other things

**Comment by ParshuM** [comment]
not done

**Comment by ParshuM** [comment]
closed
