### ISSUE TITLE
windows take away 

### ISSUE THREAD

**Issue by gajananalienhu** [anupam42/PG-DAPP#193]
without adding customer , loyalty balance  showing in receipt

**Comment by AlienHu** [comment]
![image](https://cloud.githubusercontent.com/assets/13354052/17464608/3f38a7a0-5d00-11e6-8bcc-a36f6f36cca1.png)
not able to reproduce the issue .. please explain scenario with proper screen shots

**Comment by moghribalakrishna** [comment]
Guys, check this out..

**Comment by ParshuM** [comment]
closed
