### ISSUE TITLE
employee permission add combo and remove itemkit 

### ISSUE THREAD

**Issue by gajananalienhu** [anupam42/PG-DAPP#194]
- [x] Adding New Employee Permission name to be changed to Combo from Item-kits
- [x] Display and Edit to be changed similar way

**Comment by anupam42** [comment]
Please do review issue is fixed :+1:

**Comment by gajananalienhu** [comment]
please check it properly

**Comment by gajananalienhu** [comment]
second one is done , first one is not done

**Comment by AlienHu** [comment]
both are done

**Comment by ParshuM** [comment]
closed
