### ISSUE TITLE
restaurant , loyalty spelling wrong 

### ISSUE THREAD

**Issue by gajananalienhu** [anupam42/PG-DAPP#203]
while making payment from restaurant in payment details page loyalty spelling wrong

**Comment by anupam42** [comment]
Please do review issue is fixed :+1:

**Comment by gajananalienhu** [comment]
not done 
![screenshot 2016-08-11 00 10 29](https://cloud.githubusercontent.com/assets/20481449/17566193/0feac0e6-5f58-11e6-85a9-78ad59319e1e.png)

**Comment by anupam42** [comment]
please do review issue is fixed :+1:

**Comment by Jnanumogri** [comment]
done
