### ISSUE TITLE
receivings,for return popup its showing receiving popup 

### ISSUE THREAD

**Issue by gajananalienhu** [anupam42/PG-DAPP#212]
1)in receiving screen instead of  return receipt its showing receiving  receipt  while returning 
2) while returning its showing receiving popup it should show return popup

**Comment by gajananalienhu** [comment]
check return id its showing receiving id  below company name showing receiving it should show return in both place

**Comment by gajananalienhu** [comment]
check on receipt
![screenshot 2016-08-11 00 09 03](https://cloud.githubusercontent.com/assets/20481449/17566153/e43f3fd0-5f57-11e6-966e-2aa7e922c81e.png)

**Comment by ParshuM** [comment]
closed
