### ISSUE TITLE
restaurant while taking order if we left guest and disc blank its taking submit but clock is not working 

### ISSUE THREAD

**Issue by gajananalienhu** [anupam42/PG-DAPP#214]
restaurant while taking order if we left guest and disc blank its taking submit but clock is not working 
 if we take second order than items are showing in kot

**Comment by ParshuM** [comment]
closed

**Comment by gajananalienhu** [comment]
Its taking order but clock is not working

**Comment by samurailens** [comment]
@jarvish21 : please take this up today.

**Comment by ParshuM** [comment]
Its not done

**Comment by ParshuM** [comment]
closed
