### ISSUE TITLE
while taking order Items not showing when i click on show combos

### ISSUE THREAD

**Issue by AlienHu** [anupam42/PG-DAPP#215]
while taking order if we click on combo items are not displaying , not all time some times its showing like this ( rare issue )

**Comment by gajananalienhu** [comment]
its happening sometimes not all time

**Comment by jarvish21** [comment]
not reproduceable.i tried several time was not able to see that issue

**Comment by jarvish21** [comment]
ganpati has fixed

**Comment by ParshuM** [comment]
closed
