### ISSUE TITLE
if add otg to cart its not showing popup 

### ISSUE THREAD

**Issue by gajananalienhu** [anupam42/PG-DAPP#219]
if add otg to cart its not showing popup  , its taking zero price item for payment 
![screenshot 2016-08-10 02 16 13](https://cloud.githubusercontent.com/assets/20481449/17533005/abbcf056-5ea0-11e6-9268-4b411c51f675.png)
![screenshot 2016-08-10 02 18 22](https://cloud.githubusercontent.com/assets/20481449/17533031/c7efa3e0-5ea0-11e6-9246-20b957637da4.png)

**Comment by jarvish21** [comment]
done do review

**Comment by gajananalienhu** [comment]
not done

**Comment by Jnanumogri** [comment]
Its taking zero to cart

**Comment by ParshuM** [comment]
close

**Comment by ParshuM** [comment]
clsoed
