### ISSUE TITLE
For each item in screen related to CRUD operations there must be messages displayed(error handelling)

### ISSUE THREAD

**Issue by jarvish21** [anupam42/PG-DAPP#220]

**Comment by jarvish21** [comment]
- [ ] Items
- [ ] customers
- [ ] suppliers
- [ ] restaurant

**Comment by samurailens** [comment]
@jarvish21  : Please take a note that we need to display success messages as needed.  Example : when we add an item, I dont see any message whether item is added or not. In fact, when I try to added it again, there is an error message saying 'item already exists with same name'. 

![image](https://cloud.githubusercontent.com/assets/5208310/17686130/8895594c-6387-11e6-9846-d92f8404199b.png)

I think we should start showing messages decently, if not all of them. Please call me for any clarifications.
