### ISSUE TITLE
item , i added retail price 102 its showing something different 

### ISSUE THREAD

**Issue by gajananalienhu** [anupam42/PG-DAPP#225]
rare problem item , i added retail price 102 its showing something different   like 00
![screenshot 2016-08-10 23 43 14](https://cloud.githubusercontent.com/assets/20481449/17565273/6c349704-5f54-11e6-8dd9-873c9d1f16b7.png)
![screenshot 2016-08-10 23 42 50](https://cloud.githubusercontent.com/assets/20481449/17565290/7bf305f4-5f54-11e6-8904-3123f82f8117.png)
![screenshot 2016-08-10 23 43 05](https://cloud.githubusercontent.com/assets/20481449/17565296/820f8c50-5f54-11e6-8606-67943a7621ea.png)
![screenshot 2016-08-10 23 42 35](https://cloud.githubusercontent.com/assets/20481449/17565312/92796976-5f54-11e6-8e5b-fb00680ff12b.png)

**Comment by AlienHu** [comment]
@gajananalienhu  please explain the scenario how can i reproduce this issue

**Comment by samurailens** [comment]
@gajananalienhu  : i dont see this in latest build. pls reopen if issue persists.
