### ISSUE TITLE
Make Phone number manadatory for customer,supplier and employee 

### ISSUE THREAD

**Issue by Djprem** [anupam42/PG-DAPP#228]
Make Phone number mandatory for customer,supplier and employee

**Comment by anupam42** [comment]
Please do review issue is fixed :+1:

**Comment by ParshuM** [comment]
while edit the customer its not taking submit  
![editing](https://cloud.githubusercontent.com/assets/20481136/17644356/db5c420e-61a1-11e6-8b6d-de5792a3f1dc.png)

**Comment by AlienHu** [comment]
This is done , to test it , 
1.first craete one customer or supplier or employee with one phone number , then try to edit it without changing phone number then it should not give any problem
2.try to create another person with the same phone number as previous , it should give msg saying number already exists , if so then on changing number it should succeed

**Comment by ParshuM** [comment]
closed
