### ISSUE TITLE
stores configration General settings

### ISSUE THREAD

**Issue by Jnanumogri** [anupam42/PG-DAPP#230]
![its not showing changes in receipts](https://cloud.githubusercontent.com/assets/20493114/17599539/3d1c55e6-601d-11e6-88b2-6938fa1e4c6e.png)
![when we changing the company name in general setting in stores configration](https://cloud.githubusercontent.com/assets/20493114/17599567/64e53d40-601d-11e6-94b3-791060bea836.png)

**Comment by ParshuM** [comment]
give me new build

**Comment by ParshuM** [comment]
give me new build

**Comment by ParshuM** [comment]
closed
