### ISSUE TITLE
stores configuration localization setting 

### ISSUE THREAD

**Issue by Jnanumogri** [anupam42/PG-DAPP#231]
1)when we changing the currency symbol from Rupee to $
![view item in while we updating its showing details and at the place of details its showing update](https://cloud.githubusercontent.com/assets/20493114/17600187/fc409502-601f-11e6-921c-09c288abbb3d.png)
2) but its not showing changes means its showing only Rupee symbol
![currency symbol](https://cloud.githubusercontent.com/assets/20493114/17600231/2dda783a-6020-11e6-9112-2f5711fce0c7.png)

**Comment by ParshuM** [comment]
closed
