### ISSUE TITLE
TakeAway

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#234]
its showing sales-sale(TBD) and sales-return (TBD) in screen remove this ,
![take away](https://cloud.githubusercontent.com/assets/20481136/17611505/74a93c98-6065-11e6-98e3-0db5ee0e1993.png)

**Comment by ParshuM** [comment]
its also showing Receivings screen 
![receiving](https://cloud.githubusercontent.com/assets/20481136/17611547/fbbdca28-6065-11e6-9bf1-b8c7fdbafd04.png)

**Comment by AlienHu** [comment]
This problem was bcz of rupee currency symbol , i have changed it Rs. test it and let me know

**Comment by ParshuM** [comment]
closed
