### ISSUE TITLE
# Restaurant 

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#237]
while  making payment for  OTG Price if i split bill its showing zero payment sales receipt   ( check MAPP also)
![slip](https://cloud.githubusercontent.com/assets/20481136/17644005/c4f2c9e2-6198-11e6-8294-fb0f0d8d3319.png)

**Comment by anupam42** [comment]
Please do check it its showing correct

**Comment by ParshuM** [comment]
give me new build

**Comment by ParshuM** [comment]
not done

**Comment by ParshuM** [comment]
not done

**Comment by AlienHu** [comment]
working fine
