### ISSUE TITLE
#menu item

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#239]
![forment png](https://cloud.githubusercontent.com/assets/20481136/17645083/3b962b24-61b8-11e6-9e12-109f168955a3.png)
if i view items screen its showing differences

**Comment by ParshuM** [comment]
![forment2](https://cloud.githubusercontent.com/assets/20481136/17645114/4bef0bf2-61b9-11e6-834d-6bd2ad0f691e.png)
its bi show like this

**Comment by anupam42** [comment]
Please do review issue is fixed :+1:

**Comment by ParshuM** [comment]
waiting for new build

**Comment by gajananalienhu** [comment]
parshu ram cross check it

**Comment by ParshuM** [comment]
closed
