### ISSUE TITLE
login page issue, if we click back button its logging out automatically 

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#240]
login page issue, if we click back button its logging out automatically , after logging out its showing all  modules 

![login page issue](https://cloud.githubusercontent.com/assets/20481136/17647228/06e2d384-6206-11e6-9ce3-da34a816e979.png)

**Comment by ParshuM** [comment]
not done

**Comment by ParshuM** [comment]
Not done

**Comment by saichaitanyaeruvaram** [comment]
Fixed Now

**Comment by ParshuM** [comment]
Not done

**Comment by ParshuM** [comment]
closed
