### ISSUE TITLE
#Reports 

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#249]
sales returns not showing in all reports 
![return](https://cloud.githubusercontent.com/assets/20481136/17675454/7797b8aa-6347-11e6-9a8a-6a8e23303754.png)

**Comment by ParshuM** [comment]
Not done

**Comment by saichaitanyaeruvaram** [comment]
Check if it is working now. Reopen if it not working even for 1 time.

**Comment by ParshuM** [comment]
Not done

**Comment by ParshuM** [comment]
![9999](https://cloud.githubusercontent.com/assets/20481136/20052118/7d5bd04e-a4f8-11e6-9f39-e5b4ab4b9f43.png)

**Comment by ParshuM** [comment]
not done

**Comment by ParshuM** [comment]
closed
