### ISSUE TITLE
Customer,  not displaying 

### ISSUE THREAD

**Issue by gajananalienhu** [anupam42/PG-DAPP#251]
If we add new customers,  customers not displaying

**Comment by samurailens** [comment]
@jarvish21 : please take this up today.

**Comment by jarvish21** [comment]
not reproduceable working correctly with some people

**Comment by jarvish21** [comment]
issue no #229 is same

**Comment by saichaitanyaeruvaram** [comment]
Fixed Now.

**Comment by saichaitanyaeruvaram** [comment]
Fixed Now.
