### ISSUE TITLE
Menu item,  not able to create new item 

### ISSUE THREAD

**Issue by gajananalienhu** [anupam42/PG-DAPP#252]
Menu item,  not able to create new item ,  its not taking submit  (rare problem)

**Comment by samurailens** [comment]
@gajananalienhu : try to drop the DB and then re-import the DB.  Perform your tests again and let us know.

**Comment by saichaitanyaeruvaram** [comment]
For Prepared Menu Item not able to submit

**Comment by ParshuM** [comment]
closed
