### ISSUE TITLE
While splitting bill if guest are 2 if we split the bill its showing 4guest on table 

### ISSUE THREAD

**Issue by gajananalienhu** [anupam42/PG-DAPP#253]
While splitting bill if guest are 2 if we split the bill its showing 4guest on table , , it should show only two

**Comment by saichaitanyaeruvaram** [comment]
Guests are getting duplicated. Ask how many guests for each split bill.
Make a check on total no of guests before and after split bills.

**Comment by saichaitanyaeruvaram** [comment]
reopen if u feel it is confusing/not working/improvements required.

**Comment by gajananalienhu** [comment]
on table its showing correct but on table details its showing 2 guest on each order

**Comment by ParshuM** [comment]
closed
