### ISSUE TITLE
If we place the order from inventory screen,  low inventory item not showing in place order cart 

### ISSUE THREAD

**Issue by gajananalienhu** [anupam42/PG-DAPP#260]
If we place the order from inventory screen,  low inventory item not showing in place order cart

**Comment by ParshuM** [comment]
![please](https://cloud.githubusercontent.com/assets/20481136/17711377/08b4b5c8-640f-11e6-89f6-aa1ff86d3525.png)

**Comment by AlienHu** [comment]
working fine
