### ISSUE TITLE
While creating prepared items ,  current quantity,  reorder level,  not showing but if we view same item its displaying 

### ISSUE THREAD

**Issue by gajananalienhu** [anupam42/PG-DAPP#261]
While creating prepared items ,  current quantity,  reorder level,  not showing but if we view same item its displaying 
And hide supplier filed for prepared item

**Comment by ParshuM** [comment]
![please](https://cloud.githubusercontent.com/assets/20481136/17711584/fbf25ef2-640f-11e6-85b8-3eff3a43702d.png)

**Comment by ParshuM** [comment]
![salesssss](https://cloud.githubusercontent.com/assets/20481136/17711592/05b9c5b0-6410-11e6-986e-9626f1d1d021.png)

**Comment by AlienHu** [comment]
issue is fixed ... but not getting clear picture of the screenshots attached @ParshuM  please get back
