### ISSUE TITLE
Reports Detailed Sales reports 

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#295]
alignment Detailed Sales reports 
![alignment](https://cloud.githubusercontent.com/assets/20481136/19213205/96cccff2-8d82-11e6-89f6-482165305bb5.png)

**Comment by ParshuM** [comment]
![sales8788](https://cloud.githubusercontent.com/assets/20481136/19214286/ced519c6-8d9c-11e6-8f34-22d5c84f34e9.png)

**Comment by ParshuM** [comment]
![sales8788](https://cloud.githubusercontent.com/assets/20481136/19214291/f1702a5c-8d9c-11e6-99bf-fbdabe6b3bee.png)

**Comment by samurailens** [comment]
fixed alignment .. re-open if not appearing.
