### ISSUE TITLE
ItemKit 

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#298]
if i edit  items kit and delete the items its not deleting in the cart 
![items kit](https://cloud.githubusercontent.com/assets/20481136/19213275/f93b2bd2-8d84-11e6-866d-7fa0d73aa956.png)

**Comment by ParshuM** [comment]
![items kit 2](https://cloud.githubusercontent.com/assets/20481136/19213288/83c72fda-8d85-11e6-8b09-704bb8c5f8c9.png)

**Comment by AlienHu** [comment]
@moghribalakrishna :This is sync issue , if you delete item from item kit it will not reflect untill you logout and relogin to application

**Comment by samurailens** [comment]
@GanuM any update on this? can we close it?

**Comment by AlienHu** [comment]
Complete

**Comment by ParshuM** [comment]
closed
