### ISSUE TITLE
Home delivery 

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#300]
cant able payment some orders 
![home delivery 8](https://cloud.githubusercontent.com/assets/20481136/19213312/96c16c44-8d86-11e6-9bfc-66e72be9fde2.png)

**Comment by ParshuM** [comment]
![home8](https://cloud.githubusercontent.com/assets/20481136/19213318/c041eef4-8d86-11e6-93c2-4ba6ddae6094.png)

**Comment by saichaitanyaeruvaram** [comment]
When we make Sales through Home Delivery, the transaction is not updated in CouchDB.

**Comment by saichaitanyaeruvaram** [comment]
Now sales transactions through home delivery is updated in couchdb.
Ganesh please review my commit and see if we have missed updating any other transactions.
Close this bug or comment pointing out the exact issue and sloution.

**Comment by AlienHu** [comment]
@saichaitanyaeruvaram anna i checked it .. i think its good now ...
