### ISSUE TITLE
Detailed sales reports 

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#308]
alignment problem

**Comment by anupam42** [comment]
Can i get the screenshot Sir

**Comment by saichaitanyaeruvaram** [comment]
No Back Button? Is it required? Good to have?

**Comment by GanuM** [comment]
Back Button Added to the sales History screen

**Comment by samurailens** [comment]
promoted changes required for alignment. 

@GanuM , @saichaitanyaeruvaram : this is a bigger problem. we will have to look at the templates again. These are kind very basic. They do require lot of refactoring.

**Comment by ParshuM** [comment]
![77788](https://cloud.githubusercontent.com/assets/20481136/20305162/22385f4e-ab5a-11e6-9ef2-7224a910c184.png)

**Comment by ParshuM** [comment]
closed
