### ISSUE TITLE
Items in that inventory Quantity  not showing also Quatity spelling showing wrong in edit its show Quantity

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#339]
![invetory quntity](https://cloud.githubusercontent.com/assets/20481136/19465887/0be516ec-9525-11e6-8bf5-ff7a8ed56ca8.png)

**Comment by saichaitanyaeruvaram** [comment]
Except inventory transactions, everything else updates correctly.

**Comment by saichaitanyaeruvaram** [comment]
All the fields are fixed. Inventory transactions also should update live.
Reopen this issue if any field is not updated/missing. Attach console screenshot if possible.

**Comment by ParshuM** [comment]
closed
