### ISSUE TITLE
In items kit not displaying prices amount and if i edit items kit items not deleting   also Description its not showing  

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#341]
![veg kit](https://cloud.githubusercontent.com/assets/20481136/19466285/992cb670-9527-11e6-96de-6309dca20297.png)

![desc](https://cloud.githubusercontent.com/assets/20481136/19466330/eb6d212c-9527-11e6-8b2c-5e694cddae1d.png)

**Comment by AlienHu** [comment]
ItemKits prices are fixed

**Comment by ParshuM** [comment]
price is fixed but items are not deleting

**Comment by ParshuM** [comment]
price is fixed but items are not deleting

**Comment by ParshuM** [comment]
closed
