### ISSUE TITLE
details sales reports showing blanks  

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#345]
![detailed sales repors](https://cloud.githubusercontent.com/assets/20481136/19485024/5393ea84-9577-11e6-9fea-b76f23cbab0f.png)

**Comment by saichaitanyaeruvaram** [comment]
1. Deleted items are removed from couch. Should handle if document for an item is not available.
2. Ideally we should not delete items from couchdb. We should add isDeleted flag just like in mysql.

**Comment by saichaitanyaeruvaram** [comment]
Even if it doesn't work 1 time, please reopen this issue. If possible attach console screenshot when this happens.

**Comment by ParshuM** [comment]
closed
