### ISSUE TITLE
Newly added item not updating in UI

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [anupam42/PG-DAPP#347]
Should be applicable for both retail & restaurant
1. Items Tab -> Click Show Items on some category (Ex. Fruits) 
2. Add item in the same screen. It should be same category (Fruits).
3. Flash Message comes, item added successfully. But new item card doesn't come.
4. It comes only after we go back to some tab/screen and come.

<div class=" card" ng-if="showItems && !showallItems" ng-repeat="item in itemsForCategory | filter:search" style="width: 19%;height:7%;">

itemsForCategory is not binded properly.

@samurailens :: just tell me how to handle. I will take up this.

**Comment by ParshuM** [comment]
closed
