### ISSUE TITLE
If i sale items send for payment its displaying order counter  

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#352]
![oredr](https://cloud.githubusercontent.com/assets/20481136/19528006/f1ee6238-9647-11e6-9924-b1d5c2ae02e4.png)
![counter](https://cloud.githubusercontent.com/assets/20481136/19528018/04019c7e-9648-11e6-9d2b-699c0356a896.png)

**Comment by AlienHu** [comment]
this is not the bug, this is how counter order feature is implemented
