### ISSUE TITLE
RedesignSales Receipt:: All receipts needs to be reviewed :: headers, content, alignment 

### ISSUE THREAD

**Issue by vinodshidlani** [anupam42/PG-DAPP#359]
if we sale items after that in receipt sales total and change due amount its not showing 
![h sales reciept](https://cloud.githubusercontent.com/assets/20521598/19674154/aaf44edc-9aa3-11e6-8ca0-e05f957f80fe.png)
...

**Comment by saichaitanyaeruvaram** [comment]
The entire receipt needs redesign. 
Change Due should not be shown. Terminology should change. Serial No is displayed which should not be present.

**Comment by saichaitanyaeruvaram** [comment]
fixed sales total = 0 and removed change due from the receipt as it is not applicable to homedelivery.

All the receipts needs to be reviewed.

**Comment by samurailens** [comment]
@GanuM : Can we use print receipt Template for this pop up? Just plain, black and white - no colors. ?

**Comment by AlienHu** [comment]
@ParshuM  @vinodshidlani  all the receipts except home delivery receipt should b fine ,
