### ISSUE TITLE
restaurant...counter payment 

### ISSUE THREAD

**Issue by vinodshidlani** [anupam42/PG-DAPP#360]
in counter payment ...if we send kot to kitchen after that in receipt
![counter reciept](https://cloud.githubusercontent.com/assets/20521598/19674289/ae6c0644-9aa4-11e6-9554-3e6d5c8be988.png)
 change due amount not showing...

**Comment by ParshuM** [comment]
![image](https://cloud.githubusercontent.com/assets/20481136/19768433/19d14c10-9c75-11e6-80d9-2f4d786c8d36.png)
working for me
