### ISSUE TITLE
Many modals after closing and opening again.. the fields are not cleared.

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [anupam42/PG-DAPP#369]
Add all the bugs related to clearing fields here.

1. Add New Employee Modal :: Employee Permissions, red marks
2. Receivings .. while payment comment is not cleared
3. Reports -> Detailed Reports -> Employees .. If I change the employee from default, it doesn't work
4. Reports -> Any Report -> Select Custom Date .. not working
5.customer name is not clearing even after transaction is completed in receiving s... 

@GanuM :: Ask testers to log all issues here

**Comment by ParshuM** [comment]
![555555](https://cloud.githubusercontent.com/assets/20481136/20004374/106c31ce-a2b2-11e6-93f1-3a496b95e08e.png)
![888](https://cloud.githubusercontent.com/assets/20481136/20004387/21e95a26-a2b2-11e6-98ac-830c3731602d.png)

**Comment by AlienHu** [comment]
@ParshuM  Give some description for the screens-hosts you have posted

**Comment by ParshuM** [comment]
closed
