### ISSUE TITLE
if i click shortcuts-keys alt+r but  its not removing items    same problem all screen  

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#372]
![shortcuts](https://cloud.githubusercontent.com/assets/20481136/19957971/28c17758-a1c1-11e6-9763-db2b3b868e30.png)

**Comment by AlienHu** [comment]
to delete item .. first we have to open item details and then click alt+r then it will delete , i feel this hotkey is not useful so i'm removing it , please let me know your suggestions
