### ISSUE TITLE
Restaurant.........take away 

### ISSUE THREAD

**Issue by vinodshidlani** [anupam42/PG-DAPP#377]
if i add supplier in menu items that item not displaying in take away...
![3-10-2016 v](https://cloud.githubusercontent.com/assets/20521598/19962454/b40ffdb8-a1dd-11e6-93a6-5296265a2bb2.png)

**Comment by AlienHu** [comment]
@saichaitanyaeruvaram anna this is the same problem that we discussed today morning  items will disappear once you add one item to cart

**Comment by saichaitanyaeruvaram** [comment]
#397 

I don't think it is anything to do with suppliers. SeachText object is the problem.
I've assigned 1 bug to @moghribalakrishna
