### ISSUE TITLE
Resturant..........home delivery.. sales receipt

### ISSUE THREAD

**Issue by vinodshidlani** [anupam42/PG-DAPP#387]
in sales receipt sales total and change due is not showing...
![vsales total](https://cloud.githubusercontent.com/assets/20521598/19997798/e4568ed6-a28e-11e6-8b66-42961540da56.png)

**Comment by ParshuM** [comment]
![321](https://cloud.githubusercontent.com/assets/20481136/21170150/97e281ee-c1e8-11e6-946a-23ed5addf3f3.png)
1.not done@ganesh
