### ISSUE TITLE
customer in import and exports not working properly  

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#390]
![import](https://cloud.githubusercontent.com/assets/20481136/20003580/46cdaae0-a2ad-11e6-9e40-84a2db10b3ac.png)

**Comment by saichaitanyaeruvaram** [comment]
The url path for import was wrong. Fixed the path. 
But I didn't test. If testers have any csv file check if import is working.

To be tested for items, customers and suppliers(import is hidden).

**Comment by AlienHu** [comment]
for customer both import and export is working fine

**Comment by ParshuM** [comment]
closed
