### ISSUE TITLE
Items disappearing in receivings screen

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [anupam42/PG-DAPP#397]
Steps to reproduce:
1. Goto Receivings screen.
2. Click ShowAllItems button
3. Add to cart 2 items. Click + Button in the cart to increase the number of quantities.
4. Now click - Button on any 1 of the item. Items disappear.

I debugged, the issue is because of searchText = {searchObj :{searchField: ''}}
Call @GanuM  or me for clarification the issue.

**Comment by ParshuM** [comment]
closed
