### ISSUE TITLE
Sales: Random (9/10):: In cart sometimes total value is not displayed

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [anupam42/PG-DAPP#403]
![total_display_bug_console](https://cloud.githubusercontent.com/assets/10721851/20124728/99566c1c-a64e-11e6-84b2-ebd015cef305.png)
![total_display_bug](https://cloud.githubusercontent.com/assets/10721851/20124729/9957b6a8-a64e-11e6-84b4-5fa987e459e6.png)

**Comment by ParshuM** [comment]
closed
