### ISSUE TITLE
Itemskit 

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#433]
![items kit2](https://cloud.githubusercontent.com/assets/20481136/20879496/19bd6e18-bafa-11e6-9db9-269cf5a66df4.png)
not able to search item kit

**Comment by saichaitanyaeruvaram** [comment]
@GanuM :: See if it can be fixed easily, otherwise defer it.

I worked on some bug in itemkits, I felt itemkits implementation can be better.

**Comment by ParshuM** [comment]
closed
