### ISSUE TITLE
Restaurant..suppliers 

### ISSUE THREAD

**Issue by vinodshidlani** [anupam42/PG-DAPP#453]
in suppliers account number...alphabets are not entering...ex; we have to show account numbers as follows
SBIN25251225 or SYND5822422245
![vinod](https://cloud.githubusercontent.com/assets/20521598/21038517/78925142-bdfc-11e6-824d-6afcb0204def.png)

**Comment by AlienHu** [comment]
Account number is not an bank account number , this is for account of supplier in your shop (for reference)
