### ISSUE TITLE
receipt alignment , make it in proper format   

### ISSUE THREAD

**Issue by gajananalienhu** [anupam42/PG-DAPP#485]
![tt](https://cloud.githubusercontent.com/assets/20481449/21169862/0c0da1d2-c1e6-11e6-999a-6edd4f2a54f5.png)
receipt alignment , make it in proper format   
1) tax names and % should comes below particular
2) amount should comes below price 
3) subtotal should be after discount and loyalty , and total should  be tax + subtotal

**Comment by ParshuM** [comment]
closed
