### ISSUE TITLE
not showin quantity in menu items

### ISSUE THREAD

**Issue by vinodshidlani** [anupam42/PG-DAPP#505]
in screen items are not showing quantity.......................
![dv2](https://cloud.githubusercontent.com/assets/20521598/21286520/6f315a40-c47c-11e6-89af-ebe9b0ca826e.png)

**Comment by AlienHu** [comment]
1.quantity for prepared items will be 1 always , and for others items in screen shot looks proper 
2.alignment is fixed
3.if thr is other problem then please give some more description

**Comment by ParshuM** [comment]
closed
