### ISSUE TITLE
combo cart hiding on items

### ISSUE THREAD

**Issue by vinodshidlani** [anupam42/PG-DAPP#506]
if we selected items that combo cart is hiding
![dv3](https://cloud.githubusercontent.com/assets/20521598/21286559/6ad1c33a-c47d-11e6-9657-943bdef006f4.png)

**Comment by AlienHu** [comment]
alinment is fixed , but have to take care of empty cards those are getting displayed beacause of hidden item ( for example igridient , which we cant sell ) , we will going to do that in next cycle

**Comment by ParshuM** [comment]
closed
