### ISSUE TITLE
sales cart , 

### ISSUE THREAD

**Issue by gajananalienhu** [anupam42/PG-DAPP#514]
![vm](https://cloud.githubusercontent.com/assets/20481449/21341173/302ef55a-c6b1-11e6-9518-c4ae3924fe61.png)
while editing item in cart if we click on edit option all items are enabling for edit ,, 
and if we save one item after edit all items disabling ,

**Comment by Mseenu** [comment]
still exists

**Comment by gajananalienhu** [comment]
still exists
