### ISSUE TITLE
Reports/item :: one currency symbol should show in hole app , in some screen its showing $and rs

### ISSUE THREAD

**Issue by gajananalienhu** [anupam42/PG-DAPP#52]
one currency symbol should show in hole app , in some screen its showing $and rs
![currency](https://cloud.githubusercontent.com/assets/20481449/17032992/9b6ea188-4f99-11e6-90a6-1cc7d5c8466e.png)
![gaja](https://cloud.githubusercontent.com/assets/20481449/17033022/b4feaa76-4f99-11e6-901f-79b70132748f.png)

**Comment by anupam42** [comment]
Ganesh Do verify the issue

**Comment by ParshuM** [comment]
closed
