### ISSUE TITLE
In sales details reports alignment not showing good 

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#54]
![pom1](https://cloud.githubusercontent.com/assets/20481136/17033082/01a954fc-4f9a-11e6-84b6-adf43a3fb515.png)
- [ ] Should have view payments button when there are more than one txn

**Comment by ParshuM** [comment]
not done

**Comment by samurailens** [comment]
@anupam42 : close as n when done with screenshot... since this is UI issue.

**Comment by ParshuM** [comment]
not done this issue @anupam42 verify this one more time

**Comment by anupam42** [comment]
I do need time for this issue i will take it tonight i will do :+1:

**Comment by ParshuM** [comment]
okay

**Comment by AlienHu** [comment]
@anupam42  pls check it and if it is done assign it for testing

**Comment by anupam42** [comment]
Please do review issue is fixed :+1:

**Comment by ParshuM** [comment]
closed
