### ISSUE TITLE
Employee: Permissions

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [anupam42/PG-DAPP#56]
Restaurant App
1. Create a new employee with the permissions :: Sales, Sales Stocks, Take Away, Restaurant.
2. LogIn as the employee.
3. TakeAway you can see all the items and you can add items and make sale.
4. Goto Restaurant screen. Select a table and create new order. No items are displayed.

Take Away and Restaurant Behaviour should be consistent.

**Comment by AlienHu** [comment]
@saichaitanyaeruvaram  anna pls once have look

**Comment by vinodshidlani** [comment]
closed
