### ISSUE TITLE
Take Away :: Add Customer Screen Freeze

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [anupam42/PG-DAPP#57]
1. Take Away Screen
2. Click the 3 dots
3. Select Add Customer
4. In the Customer list, click view

Now the screen freezes, can't come out of it unless I kill the application

GoTo -> Restaurant Screen -> Select Table -> Give Details -> Now we are in sales screen
Add Customer .. Click View and Then Click Cancel, we can't go back to sales screen

If this is a duplicate issue, mark as duplicate and close the issue.

**Comment by samurailens** [comment]
@jarvish21 : please follow up quickly.

**Comment by ParshuM** [comment]
closed
