### ISSUE TITLE
Back Button issue

### ISSUE THREAD

**Issue by srinuravilla** [anupam42/PG-DAPP#62]
hi Team,

Back button from Billing is directly going to Main screen.
please find the attached screen shots let me know Regarding full information..

Step1: form below screen if i am clicking back button directly it is going to step2
![backbutton gives main screen](https://cloud.githubusercontent.com/assets/20645998/17114411/7ab0b428-52cc-11e6-9a15-42699617e085.png)

step 2: it is directly redirecting to below screen

![backbuttongives main screen](https://cloud.githubusercontent.com/assets/20645998/17114412/7ab17f7a-52cc-11e6-9de5-42e537f681b4.png)

Step 3: actual screen to display is below screen

![backbuutongives main screen](https://cloud.githubusercontent.com/assets/20645998/17114444/9814bd8e-52cc-11e6-87a8-14a723ec61fd.png)

**Comment by samurailens** [comment]
@GanuM : can we store states programatically? Can we track each state ( a page ) ?

**Comment by AlienHu** [comment]
@srinuravilla we can store states in variables

**Comment by Jnanumogri** [comment]
assign to Gajanan

**Comment by ParshuM** [comment]
closed
