### ISSUE TITLE
New added item is displaying out of cart

### ISSUE THREAD

**Issue by srinuravilla** [anupam42/PG-DAPP#63]
hi Team,,

new added item to he sales cart is disaplaying out of the border (ex..,if we add more than 4 items the after that newly added item should be display it is not displaying.

we can show recently added item as LIFO manner or FIFO manner it is easy to understood by sales guy.

Feature: if you giving some different color for newly added item in cart it is better to easily identify

![recentlyaddediemnotvisbilngoncart](https://cloud.githubusercontent.com/assets/20645998/17114748/e765c120-52cd-11e6-9046-3b2e70eb0674.png)

**Comment by samurailens** [comment]
check if its plain CSS or coding issue. Please validate.

**Comment by AlienHu** [comment]
We can display newly added item at the bottom of the cart separately as we displaying it on footer

**Comment by ParshuM** [comment]
closed

**Comment by ParshuM** [comment]
closed
