### ISSUE TITLE
Footer Displaying

### ISSUE THREAD

**Issue by srinuravilla** [anupam42/PG-DAPP#64]
Hi Team,

we are displaying recently added item in footer.
the bug what i have seen is, suppose if it is first time we adding item to cart it is displaying in the footer. if we added the same item after adding the some other item. the already added item (that is first item) is not displaying in footer.

below image last i added item is srinu but footer it is dispalying some other item

![footer](https://cloud.githubusercontent.com/assets/20645998/17115168/c6d2efbc-52cf-11e6-896e-78b42e90a7f6.png)

**Comment by AlienHu** [comment]
Fixed

**Comment by ParshuM** [comment]
closed
