### ISSUE TITLE
Shortcut Popup out of the screen

### ISSUE THREAD

**Issue by srinuravilla** [anupam42/PG-DAPP#65]
Hi Team,

we are displaying shortcut keys by  clicking shift+? that window is out of the screen.
if we have more shortcuts if it is going out of the screen please place a  scroll bar. it is look good.

![shortcutwindowalignmentissue](https://cloud.githubusercontent.com/assets/20645998/17115262/28133c8c-52d0-11e6-9b63-44484caf65d5.png)

**Comment by samurailens** [comment]
# CSS/UI

@anupam42 : Please add it to cumulative CSS changes. We will take this and other CSS changes in one-shot.

@srinuravilla : Please tag issues like this as UI/UX/CSS from now.

**Comment by ParshuM** [comment]
its not done @anupam42

**Comment by ParshuM** [comment]
its not done

**Comment by ParshuM** [comment]
verify one more time @anupam42

**Comment by anupam42** [comment]
Please do review issue is fixed :+1: 
![shortcut_alligned](https://cloud.githubusercontent.com/assets/16332264/17367526/e59669e4-59ad-11e6-89e4-8eaf38239e1c.png)

**Comment by ParshuM** [comment]
closed
