### ISSUE TITLE
Regarding Combo pack 

### ISSUE THREAD

**Issue by srinuravilla** [anupam42/PG-DAPP#66]
Hi team,

when i am going too add the combo pack there is no fields like ADD COMBO and DELETE COMBO.
please find the below screen shot.

![combopackneed add and delete combo](https://cloud.githubusercontent.com/assets/20645998/17115473/11a0f3c6-52d1-11e6-9fa9-2f4f285161e2.png)

**Comment by jarvish21** [comment]
regarding name in popover i changed it to add new combo and delete combo is present if we view item...
we have delete combo

**Comment by ParshuM** [comment]
closed
