### ISSUE TITLE
Adding Supplier Issue

### ISSUE THREAD

**Issue by srinuravilla** [anupam42/PG-DAPP#67]
Hi Team,

there is a bug during adding suppliers in restaurant app.

the issue is it is showing 2 suppliers as like below screen shot.

![supplierissue](https://cloud.githubusercontent.com/assets/20645998/17115533/575e30d6-52d1-11e6-9ffd-2d05d9e3015c.png)

if i am adding another 1 supplier it is showing total 4 suppliers please find below screen shot

![supplierafter adding](https://cloud.githubusercontent.com/assets/20645998/17115610/cae5b61e-52d1-11e6-94e9-0682ff7fe6bc.png)

**Comment by jarvish21** [comment]
may be refresh issue

**Comment by ParshuM** [comment]
closed
