### ISSUE TITLE
Stock Quantity issue

### ISSUE THREAD

**Issue by srinuravilla** [anupam42/PG-DAPP#68]
Hi team,

we are giving total stock details for item.
in restaurant  sales tab  that quantity is not displaying on the item . how the sale guy know that product inventory is low.
the actual bug is i am not able to add one particular  item to the cart as keep on investigation i g=found that particular product inventory is "0" .
we are not displaying popup once the item reaches record level

Ex: here the coco-cola item i am not able to add to cart due to it has low inventory 
we have display popup like no items are present in inventory after clicking the item when item reaches to "0".

![quantiytydisplaying](https://cloud.githubusercontent.com/assets/20645998/17115872/edfe3e0e-52d2-11e6-9509-f503d6a54a6e.png)

**Comment by samurailens** [comment]
@srinuravilla  : This bug fix is in progress. 
@GanuM : close this when done anna.

**Comment by ParshuM** [comment]
closed
