### ISSUE TITLE
Report issue

### ISSUE THREAD

**Issue by praveenpss** [anupam42/PG-DAPP#73]
hi team,

alignment is out of border please fix.

in report payment and discount fields are out of border in summary report

![alignment isues](https://cloud.githubusercontent.com/assets/20493150/17127076/6ecd3952-5320-11e6-97ba-8518fceddd4b.png)

![alignmnet issues](https://cloud.githubusercontent.com/assets/20493150/17127079/74b1c0c2-5320-11e6-88bb-4037cf0832d4.png)

**Comment by ParshuM** [comment]
closed
