### ISSUE TITLE
Negative Quantity in Cart for Item with On the Go Price

### ISSUE THREAD

**Issue by samurailens** [anupam42/PG-DAPP#74]
![image](https://cloud.githubusercontent.com/assets/5208310/17144843/d225657e-5375-11e6-9f87-e51fa9e59eb2.png)

As you can see from the screen shot, the quantity is -1.

Steps : 
1. In fresh DB, add a single item - with On the Go pricing strategy. 
2. In sales screen, add this single item to cart.  You will see the quantity is -1.

**Comment by moghribalakrishna** [comment]
Ganu, This is Blocker fix this asap.

**Comment by AlienHu** [comment]
![image](https://cloud.githubusercontent.com/assets/13354052/17168518/6cd45cc6-5400-11e6-8024-ef712ccf0379.png)
I'm not able to reproduce this issue , Im adding single item with otg , add adding it to cart in sales , i dont see it in negetive qty

**Comment by samurailens** [comment]
This is reproducible in quick succession. We will close this for now and check it back after a while.
