### ISSUE TITLE
in report alignment issue

### ISSUE THREAD

**Issue by srinuravilla** [anupam42/PG-DAPP#75]
hi team,,,

alignment is not proper plesea find the below screen shot .

![alignment isues](https://cloud.githubusercontent.com/assets/20645998/17151374/ff36ae22-5390-11e6-983c-9c15cbc097c9.png)

![alignmnet issues](https://cloud.githubusercontent.com/assets/20645998/17151381/06492802-5391-11e6-8e09-cb9b536f49e7.png)

**Comment by ParshuM** [comment]
closed
