### ISSUE TITLE
take-away

### ISSUE THREAD

**Issue by praveenpss** [anupam42/PG-DAPP#78]
hi team 

when we make payment bill detail column cancel button made one box
![canceland comments](https://cloud.githubusercontent.com/assets/20493150/17152420/557c69bc-5395-11e6-8c40-2a747aa1e7ea.png)

  cancel make box

**Comment by moghribalakrishna** [comment]
Srinu, Try to put the lables, (i.e. Resturant or Retail etc), that would better for separating the issues accordingly.

**Comment by moghribalakrishna** [comment]
Here Payment info on the "Bill Detail"should be made distinct box by giving more appropriate colors to cancel and payment info.
ex:
"Cancel" should be Renamed as "Cancel Payment"

**Comment by moghribalakrishna** [comment]
This change should be done across all Sales screens.

**Comment by ParshuM** [comment]
closed
