### ISSUE TITLE
Need reports fields icons

### ISSUE THREAD

**Issue by srinuravilla** [anupam42/PG-DAPP#81]
hi Team,

please provide icons in the reports for every  field..

![reports](https://cloud.githubusercontent.com/assets/20645998/17163273/3aa27744-53db-11e6-8184-2a97a5d53d2d.png)

**Comment by moghribalakrishna** [comment]
Anup, check out font awesome glyph icons and see if we can have better icons and fonts.

**Comment by anupam42** [comment]
Please Do review :+1:

**Comment by ParshuM** [comment]
not done

**Comment by ParshuM** [comment]
not done they not provide new app

**Comment by ParshuM** [comment]
closed
