### ISSUE TITLE
phone nummber

### ISSUE THREAD

**Issue by srinuravilla** [anupam42/PG-DAPP#84]
change below text from customer contact info to contact phone number.

![contcttakingmorethan10numbers](https://cloud.githubusercontent.com/assets/20645998/17163985/b0022e66-53e1-11e6-981c-b399367f8363.png)

**Comment by ParshuM** [comment]
Not done

**Comment by ParshuM** [comment]
not done

**Comment by ParshuM** [comment]
closed
