### ISSUE TITLE
home delivery 

### ISSUE THREAD

**Issue by srinuravilla** [anupam42/PG-DAPP#85]
in home delivery checkout filed is not required. 
it is  coming once the customer added for given delivery and it  is disabling  automatically after 15 seconds.

![checkoutis not needed](https://cloud.githubusercontent.com/assets/20645998/17164503/7259ced4-53e6-11e6-8646-72d401f5bca6.png)

**Comment by jarvish21** [comment]
fixed do-review

**Comment by ParshuM** [comment]
not done
