### ISSUE TITLE
alignment of cart

### ISSUE THREAD

**Issue by AlienHu** [anupam42/PG-DAPP#86]
As u can see , if i give longer name for item and add it to cart , it will b missaligned in 

![image](https://cloud.githubusercontent.com/assets/13354052/17169549/a3c139e8-5405-11e6-9fa5-dafea04537da.png)

**Comment by anupam42** [comment]
Please do review issue is fixed :+1:

**Comment by ParshuM** [comment]
not done they not provide new app

**Comment by ParshuM** [comment]
not done they not provide new app
