### ISSUE TITLE
Sale Receipt 

### ISSUE THREAD

**Issue by AlienHu** [anupam42/PG-DAPP#89]
- [x] Hide Discount column if thr is no discount for sale items
- [x] Show total BIll Amt
- [x] Change Due
- [x] Greeting Message
- [x] Remove negetive sign from received amt in receipt

**Comment by ParshuM** [comment]
not done they not given new app

**Comment by ParshuM** [comment]
![recipt](https://cloud.githubusercontent.com/assets/20481136/17223641/263ac13a-551b-11e6-80ec-768f28083b4d.png)

**Comment by ParshuM** [comment]
see like that showing this

**Comment by ParshuM** [comment]
closed

**Comment by samurailens** [comment]
@gajananalienhu , @ParshuM : open if needed
