### ISSUE TITLE
Employees

### ISSUE THREAD

**Issue by vinodshidlani** [anupam42/PG-DAPP#90]
if we give permission to employee  for sales, sales stock then it ill be not taking permission........ sales and sales stocks are only for retailers not for resturant ill u hide that models..

![employees](https://cloud.githubusercontent.com/assets/20521598/17181646/87062faa-543e-11e6-98e1-572f9d4ed9b3.png)

**Comment by AlienHu** [comment]
@jarvish21  hide sales permission from add employee in restaurant app , this should fix this issue

**Comment by ParshuM** [comment]
closed
