### ISSUE TITLE
make edit button on kot's menu

### ISSUE THREAD

**Issue by ParshuM** [anupam42/PG-DAPP#97]
![edit button](https://cloud.githubusercontent.com/assets/20481136/17224984/ce95a3f4-5520-11e6-8e0e-279008cfe24f.png)

**Comment by AlienHu** [comment]
@anupam42  remove that crossed text from those category cards .. its not looking good

**Comment by anupam42** [comment]
Please do review issue is fixed :+1:

**Comment by ParshuM** [comment]
closed
