### ISSUE TITLE
report

### ISSUE THREAD

**Issue by praveenpss** [anupam42/PG-DAPP#99]
hi team report thire will give some icons it will looking good 

![reports](https://cloud.githubusercontent.com/assets/20493150/17226045/155226ba-5525-11e6-8ca7-b56ee8fe7a11.png)

**Comment by AlienHu** [comment]
@praveenpss i think @anupam42  has already did this , @anupam42  please commit your changes and give new build for testing

**Comment by ParshuM** [comment]
closed
